#pragma once
#define IDI_PREVIEW   101
#define IDR_SHIKI_JS  200
#define IDR_ONIG_WASM 201
#define IDR_NMD_HTML  202
#define IDR_MERMAID_JS 203
#define IDR_KATEX_JS  204
#define IDR_KATEX_CSS 205

#define IDR_KATEX_FONT_AMS_REGULAR           210
#define IDR_KATEX_FONT_CALIGRAPHIC_BOLD      211
#define IDR_KATEX_FONT_CALIGRAPHIC_REGULAR   212
#define IDR_KATEX_FONT_FRAKTUR_BOLD          213
#define IDR_KATEX_FONT_FRAKTUR_REGULAR       214
#define IDR_KATEX_FONT_MAIN_BOLD             215
#define IDR_KATEX_FONT_MAIN_BOLDITALIC       216
#define IDR_KATEX_FONT_MAIN_ITALIC           217
#define IDR_KATEX_FONT_MAIN_REGULAR          218
#define IDR_KATEX_FONT_MATH_BOLDITALIC       219
#define IDR_KATEX_FONT_MATH_ITALIC           220
#define IDR_KATEX_FONT_SANSSERIF_BOLD        221
#define IDR_KATEX_FONT_SANSSERIF_ITALIC      222
#define IDR_KATEX_FONT_SANSSERIF_REGULAR     223
#define IDR_KATEX_FONT_SCRIPT_REGULAR        224
#define IDR_KATEX_FONT_SIZE1_REGULAR         225
#define IDR_KATEX_FONT_SIZE2_REGULAR         226
#define IDR_KATEX_FONT_SIZE3_REGULAR         227
#define IDR_KATEX_FONT_SIZE4_REGULAR         228
#define IDR_KATEX_FONT_TYPEWRITER_REGULAR    229

